name: very_good_coffee
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.4
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  uuid: ^4.4.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  coverage: ^1.9.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
